# Generated by Django 4.0.7 on 2022-08-18 08:29

import api.mssql_uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('slug', api.mssql_uuid.MssqlUUID(db_column='goodsID', default=None, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_column='goods_code', max_length=15, verbose_name='Barcode')),
                ('name', models.CharField(db_column='goods_name', max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(db_column='goods_price', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'GoodsPrices',
                'ordering': ['barcode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('slug', api.mssql_uuid.MssqlUUID(db_column='Goods_CategoryId', default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Goods_Category', max_length=20, verbose_name='Category')),
            ],
            options={
                'db_table': 'Goods_Category',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('slug', api.mssql_uuid.MssqlUUID(db_column='SupplierID', default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Org_Name', max_length=20, verbose_name='Supplier')),
            ],
            options={
                'db_table': 'Supplier',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wristbands',
            fields=[
                ('id', models.CharField(db_column='Wrist_NUM', default=None, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(db_column='Top_up_rest', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'Wristbands',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
