# Generated by Django 4.0.7 on 2022-08-18 14:23

import api.mssql_uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izoor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('slug', api.mssql_uuid.MssqlUUID(db_column='OrganizationID', default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Org_Name', max_length=200, unique=True, verbose_name='Company')),
                ('address', models.CharField(blank=True, db_column='Org_Address', max_length=200)),
                ('overdraft', models.BooleanField(db_column='CanOverdraft')),
            ],
            options={
                'db_table': 'Organization',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
