# Generated by Django 4.0.7 on 2022-08-21 00:10

import api.mssql_uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('izoor', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSRight',
            fields=[
                ('right', models.CharField(db_column='ListRight', editable=False, max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=50)),
            ],
            options={
                'db_table': 'LocalUserRight',
                'ordering': ['right'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='POSUser',
            fields=[
                ('slug', api.mssql_uuid.MssqlUUID(db_column='UserID', default=None, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='EmpID', max_length=5, unique=True)),
                ('name', models.CharField(db_column='UserName', max_length=50, unique=True)),
                ('pin', models.IntegerField(db_column='Pin')),
            ],
            options={
                'db_table': 'LocalUsers',
                'ordering': ['user_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='izoor.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
